// Verbatim extraction of wizard schemas from design reference.
export const STATES = ['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY'];

export type FieldType = 'text'|'email'|'tel'|'date'|'select'|'chips'|'multi'|'textarea';

export interface WizardField { k: string; label: string; type: FieldType; req: boolean; col: 1|2; options?: string[]; ph?: string; help?: string; }
export interface WizardStep { id: string; icon: string; title: string; desc: string; fields: WizardField[]; }
export interface ProductSchema { product: string; code: string; refIdPrefix: string; steps: WizardStep[]; }

export const AUTO: ProductSchema = { product: 'Auto', code: 'AUT', refIdPrefix: 'AUT-', steps: [
  { id:'contact', icon:'user', title:'About you', desc:"Who are we quoting? We'll use this to reach you with your rate.", fields:[
    {k:'firstName',label:'First name',type:'text',req:true,col:1},
    {k:'lastName',label:'Last name',type:'text',req:true,col:1},
    {k:'dob',label:'Date of birth',type:'date',req:true,col:1},
    {k:'maritalStatus',label:'Marital status',type:'select',req:true,col:1,options:['Single','Married','Divorced','Widowed']},
    {k:'ssn',label:'Social Security number',type:'text',req:true,col:1,ph:'XXX-XX-XXXX',help:'Used to pull carrier-required reports (driving record, insurance history). Handled per our privacy policy.'},
    {k:'phone',label:'Phone',type:'tel',req:true,col:1,ph:'(573) 000-0000'},
    {k:'email',label:'Email',type:'email',req:true,col:1,ph:'you@email.com'},
    {k:'street',label:'Home / garaging address',type:'text',req:true,col:2,ph:'Street address'},
    {k:'city',label:'City',type:'text',req:true,col:1},
    {k:'state',label:'State',type:'select',req:true,col:1,options:STATES},
    {k:'zip',label:'ZIP code',type:'text',req:true,col:1,ph:'63869'},
  ]},
  { id:'vehicle', icon:'car', title:'Your vehicle', desc:'Tell us about the vehicle you want covered. Have another? Add it in the notes on the last step.', fields:[
    {k:'vehYear',label:'Year',type:'text',req:true,col:1,ph:'2022'},
    {k:'vehMake',label:'Make',type:'text',req:true,col:1,ph:'Chevrolet'},
    {k:'vehModel',label:'Model',type:'text',req:true,col:1,ph:'Silverado 1500'},
    {k:'vehTrim',label:'Trim (optional)',type:'text',req:false,col:1,ph:'LT'},
    {k:'vin',label:'VIN (optional, speeds things up)',type:'text',req:false,col:2,ph:'17-character VIN'},
    {k:'ownership',label:'Do you own, finance, or lease it?',type:'chips',req:true,col:2,options:['Own outright','Financing','Lease']},
    {k:'primaryUse',label:'Primary use',type:'select',req:true,col:1,options:['Commute to work/school','Pleasure / personal','Business / work use','Rideshare / delivery']},
    {k:'annualMileage',label:'Miles driven per year',type:'select',req:true,col:1,options:['Under 5,000','5,000–10,000','10,000–15,000','15,000–20,000','Over 20,000']},
  ]},
  { id:'history', icon:'history', title:'Driving history', desc:'This helps us match you to the right carrier and rate. Be as accurate as you can.', fields:[
    {k:'licenseStatus',label:'License status',type:'select',req:true,col:1,options:['Valid','Permit','Suspended','Expired','Foreign / international']},
    {k:'dlNumber',label:'Driver’s license number',type:'text',req:true,col:1},
    {k:'dlState',label:'License state',type:'select',req:true,col:1,options:STATES},
    {k:'yearsLicensed',label:'Years licensed',type:'select',req:true,col:1,options:['Less than 1','1–3','3–5','5–10','More than 10']},
    {k:'accidents',label:'At-fault accidents (last 5 yrs)',type:'select',req:true,col:1,options:['0','1','2','3 or more']},
    {k:'violations',label:'Tickets / violations (last 5 yrs)',type:'select',req:true,col:1,options:['0','1','2','3 or more']},
    {k:'dui',label:'Any DUI/DWI in the last 5 years?',type:'chips',req:true,col:2,options:['Yes','No']},
    {k:'currentlyInsured',label:'Do you have auto insurance right now?',type:'chips',req:true,col:2,options:['Yes','No']},
    {k:'currentCarrier',label:'Current / most recent carrier',type:'text',req:false,col:1,ph:'e.g. Progressive'},
    {k:'continuousCoverage',label:'Continuous coverage length',type:'select',req:false,col:1,options:['None / new driver','Under 6 months','6–12 months','1–3 years','3+ years']},
  ]},
  { id:'coverage', icon:'sliders', title:'Coverage you want', desc:"Not sure? Pick your best guess — we'll walk through the specifics when we call.", fields:[
    {k:'coverageType',label:'Coverage level',type:'chips',req:true,col:2,options:['State minimum','Standard (liab + collision + comp)','Full coverage']},
    {k:'bodilyInjury',label:'Bodily injury liability limit',type:'select',req:true,col:1,options:['State minimum','25/50','50/100','100/300','250/500'],help:'Per person / per accident, in thousands.'},
    {k:'propertyDamage',label:'Property damage limit',type:'select',req:true,col:1,options:['State minimum','$25,000','$50,000','$100,000']},
    {k:'collisionDeductible',label:'Collision deductible',type:'select',req:true,col:1,options:['No collision','$250','$500','$1,000','$2,000']},
    {k:'compDeductible',label:'Comprehensive deductible',type:'select',req:true,col:1,options:['No comprehensive','$250','$500','$1,000','$2,000']},
    {k:'uninsuredMotorist',label:'Add uninsured / underinsured motorist?',type:'chips',req:true,col:2,options:['Yes','No','Not sure']},
    {k:'medicalPayments',label:'Medical payments coverage',type:'select',req:false,col:1,options:['None','$1,000','$5,000','$10,000']},
    {k:'extras',label:'Optional add-ons',type:'multi',req:false,col:2,options:['Roadside assistance','Rental reimbursement','Gap coverage','Full glass','New car replacement'],help:'Pick any that interest you.'},
    {k:'startDate',label:'When do you want coverage to start?',type:'date',req:true,col:1},
    {k:'additionalDrivers',label:'Other drivers to include?',type:'select',req:false,col:1,options:['Just me','1 additional','2 additional','3 or more']},
  ]},
] };

export const HOME: ProductSchema = { product: 'Home', code: 'HOM', refIdPrefix: 'HOM-', steps: [
  { id:'contact', icon:'user', title:'You & the property', desc:"Who are we quoting, and where's the home? We'll use this to reach you with your rate.", fields:[
    {k:'firstName',label:'First name',type:'text',req:true,col:1},
    {k:'lastName',label:'Last name',type:'text',req:true,col:1},
    {k:'phone',label:'Phone',type:'tel',req:true,col:1,ph:'(573) 000-0000'},
    {k:'email',label:'Email',type:'email',req:true,col:1,ph:'you@email.com'},
    {k:'ssn',label:'Social Security number',type:'text',req:true,col:1,ph:'XXX-XX-XXXX',help:'Used to pull carrier-required reports (claims and insurance history). Handled per our privacy policy.'},
    {k:'dlNumber',label:'Driver’s license number',type:'text',req:true,col:1},
    {k:'street',label:'Property address',type:'text',req:true,col:2,ph:'Street address of the home to insure'},
    {k:'city',label:'City',type:'text',req:true,col:1},
    {k:'state',label:'State',type:'select',req:true,col:1,options:STATES},
    {k:'zip',label:'ZIP code',type:'text',req:true,col:1,ph:'63869'},
  ]},
  { id:'property', icon:'home', title:'About the home', desc:'Tell us what kind of home it is and how it’s built. Estimates are fine where you’re unsure.', fields:[
    {k:'propertyType',label:'Property type',type:'select',req:true,col:1,options:['Single-family','Townhouse','Condo','Duplex / multi-family','Manufactured / mobile home']},
    {k:'occupancy',label:'How is it occupied?',type:'select',req:true,col:1,options:['Primary residence','Secondary / seasonal','Rental / tenant-occupied','Vacant']},
    {k:'yearBuilt',label:'Year built',type:'text',req:true,col:1,ph:'1998'},
    {k:'squareFootage',label:'Square footage (living area)',type:'text',req:true,col:1,ph:'1,850'},
    {k:'stories',label:'Number of stories',type:'select',req:true,col:1,options:['1','1.5','2','3 or more']},
    {k:'ownershipLength',label:'How long have you owned it?',type:'select',req:true,col:1,options:['Buying now / closing soon','Less than 1 year','1–5 years','5–10 years','More than 10 years']},
    {k:'constructionType',label:'Construction type',type:'select',req:true,col:1,options:['Wood frame','Brick / masonry','Brick veneer','Stucco','Log','Other']},
    {k:'roofType',label:'Roof material',type:'select',req:true,col:1,options:['Asphalt shingle','Metal','Tile','Wood shake','Flat / membrane','Other']},
    {k:'roofAge',label:'Roof age',type:'select',req:true,col:1,options:['0–5 years','6–10 years','11–15 years','16–20 years','Over 20 years','Not sure']},
    {k:'foundationType',label:'Foundation type',type:'select',req:true,col:1,options:['Slab','Crawl space','Full basement','Partial basement','Pier & beam']},
    {k:'garageType',label:'Garage',type:'select',req:false,col:1,options:['None','Attached','Detached','Carport']},
    {k:'basementFinished',label:'Is the basement finished?',type:'select',req:false,col:1,options:['No basement','Unfinished','Partially finished','Fully finished']},
  ]},
  { id:'systems', icon:'wrench', title:'Systems & safety', desc:'Carriers rate on the age and condition of the home’s major systems, plus how it’s protected.', fields:[
    {k:'heatingType',label:'Primary heat source',type:'select',req:true,col:1,options:['Forced air (gas)','Forced air (electric)','Heat pump','Boiler / radiant','Baseboard electric','Wood / pellet']},
    {k:'heatingAge',label:'Age of heating system',type:'select',req:true,col:1,options:['0–5 years','6–10 years','11–15 years','Over 15 years','Not sure']},
    {k:'electricalAmps',label:'Electrical service',type:'select',req:true,col:1,options:['100 amp','150 amp','200 amp','Over 200 amp','Fuses / knob & tube','Not sure']},
    {k:'wiringUpdated',label:'Wiring updated in last 25 yrs?',type:'chips',req:true,col:1,options:['Yes','No','Not sure']},
    {k:'plumbingType',label:'Plumbing type',type:'select',req:true,col:1,options:['Copper','PEX','PVC / CPVC','Galvanized','Polybutylene','Not sure']},
    {k:'plumbingUpdated',label:'Plumbing updated in last 25 yrs?',type:'chips',req:true,col:1,options:['Yes','No','Not sure']},
    {k:'waterHeaterAge',label:'Water heater age',type:'select',req:false,col:1,options:['0–5 years','6–10 years','Over 10 years','Tankless','Not sure']},
    {k:'smokeDetectors',label:'Smoke detectors installed?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'securitySystem',label:'Security / alarm system?',type:'select',req:true,col:2,options:['None','Local alarm','Monitored burglar','Monitored fire','Monitored fire & burglar']},
  ]},
  { id:'risk', icon:'alert', title:'Risk & features', desc:'A few things that affect your rate and eligibility. Answer honestly — it protects your claim later.', fields:[
    {k:'distanceToFireStation',label:'Distance to nearest fire station',type:'select',req:true,col:1,options:['Under 1 mile','1–5 miles','Over 5 miles','Not sure']},
    {k:'distanceToHydrant',label:'Distance to nearest hydrant',type:'select',req:true,col:1,options:['Under 500 ft','500–1000 ft','Over 1000 ft','No hydrant nearby']},
    {k:'floodZone',label:'Is the home in a flood zone?',type:'chips',req:true,col:2,options:['Yes','No','Not sure'],help:'Standard home policies don’t cover flood — we can quote separate flood coverage if needed.'},
    {k:'pool',label:'Swimming pool on the property?',type:'chips',req:true,col:1,options:['None','Above-ground','In-ground']},
    {k:'trampoline',label:'Trampoline on the property?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'woodStove',label:'Wood stove or fireplace?',type:'chips',req:false,col:1,options:['None','Fireplace','Wood stove','Both']},
    {k:'dog',label:'Any dogs?',type:'select',req:false,col:1,options:['No dog','Dog — no bite history','Dog — restricted breed','Prefer not to say']},
    {k:'businessOnPremises',label:'Business run from the home?',type:'chips',req:false,col:2,options:['Yes','No']},
  ]},
  { id:'coverage', icon:'sliders', title:'Coverage & history', desc:"Tell us the coverage you're after and your recent history. We'll fine-tune the specifics on our call.", fields:[
    {k:'currentlyInsured',label:'Do you have home insurance now?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'claims5yr',label:'Claims in the last 5 years',type:'select',req:true,col:1,options:['0','1','2','3 or more']},
    {k:'currentCarrier',label:'Current / most recent carrier',type:'text',req:false,col:1,ph:'e.g. Shelter, State Farm'},
    {k:'mortgagee',label:'Is there a mortgage on the home?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'dwellingCoverage',label:'Dwelling coverage (rebuild cost)',type:'select',req:true,col:1,options:['Not sure — help me','Under $150k','$150k–$250k','$250k–$400k','$400k–$600k','Over $600k'],help:'What it would cost to rebuild, not market value.'},
    {k:'deductible',label:'Preferred deductible',type:'select',req:true,col:1,options:['$500','$1,000','$2,500','$5,000','1% of dwelling','2% of dwelling']},
    {k:'personalProperty',label:'Personal property coverage',type:'select',req:false,col:1,options:['Standard (50% of dwelling)','Enhanced (70%)','Maximum (75%+)','Not sure']},
    {k:'liabilityLimit',label:'Personal liability limit',type:'select',req:true,col:1,options:['$100,000','$300,000','$500,000','$1,000,000']},
    {k:'endorsements',label:'Coverage add-ons you want',type:'multi',req:false,col:2,options:['Water backup / sump overflow','Replacement cost on contents','Extended dwelling replacement','Scheduled jewelry / valuables','Service line coverage','Equipment breakdown','Identity theft'],help:'Pick any that interest you.'},
    {k:'startDate',label:'When do you want coverage to start?',type:'date',req:true,col:1},
    {k:'notes',label:'Anything else we should know?',type:'textarea',req:false,col:2,ph:'Recent renovations, additional structures, other vehicles or properties to bundle…'},
  ]},
] };

export const COMMERCIAL: ProductSchema = { product: 'Commercial', code: 'COM', refIdPrefix: 'COM-', steps: [
  { id:'contact', icon:'user', title:'About you & your business', desc:"Who are we quoting, and how do we reach you?", fields:[
    {k:'firstName',label:'First name',type:'text',req:true,col:1},
    {k:'lastName',label:'Last name',type:'text',req:true,col:1},
    {k:'title',label:'Your title / role',type:'text',req:true,col:1,ph:'Owner, Manager'},
    {k:'phone',label:'Phone',type:'tel',req:true,col:1,ph:'(573) 000-0000'},
    {k:'email',label:'Email',type:'email',req:true,col:1,ph:'you@business.com'},
    {k:'businessName',label:'Legal business name',type:'text',req:true,col:1,ph:'ACME LLC'},
    {k:'dba',label:'DBA / trade name (optional)',type:'text',req:false,col:1},
    {k:'website',label:'Website (optional)',type:'text',req:false,col:1,ph:'www.example.com'},
    {k:'ssn',label:'Owner Social Security number',type:'text',req:true,col:1,ph:'XXX-XX-XXXX',help:'Used for owner verification and carrier-required reports. Handled per our privacy policy.'},
    {k:'dlNumber',label:'Owner’s driver’s license number',type:'text',req:true,col:1},
    {k:'street',label:'Business address',type:'text',req:true,col:2,ph:'Primary business street address'},
    {k:'city',label:'City',type:'text',req:true,col:1},
    {k:'state',label:'State',type:'select',req:true,col:1,options:STATES},
    {k:'zip',label:'ZIP code',type:'text',req:true,col:1,ph:'63869'},
  ]},
  { id:'business', icon:'building', title:'Your business', desc:'Tell us about the operation so we can match the right carriers.', fields:[
    {k:'entityType',label:'Business entity type',type:'select',req:true,col:1,options:['Sole proprietor','Partnership','LLC','S-Corporation','C-Corporation','Non-profit']},
    {k:'businessType',label:'Type of business / industry',type:'text',req:true,col:1,ph:'e.g. HVAC contractor, restaurant, retail'},
    {k:'yearsInBusiness',label:'Years in business',type:'select',req:true,col:1,options:['Startup / under 1 year','1–3 years','3–5 years','5–10 years','More than 10 years']},
    {k:'numEmployees',label:'Number of employees',type:'select',req:true,col:1,options:['Just owner(s)','1–5','6–10','11–25','26–50','More than 50']},
    {k:'annualRevenue',label:'Annual revenue',type:'select',req:true,col:1,options:['Under $100k','$100k–$500k','$500k–$1M','$1M–$5M','Over $5M']},
    {k:'annualPayroll',label:'Annual payroll',type:'select',req:true,col:1,options:['Under $50k','$50k–$250k','$250k–$1M','Over $1M']},
    {k:'premises',label:'Do you own or lease your premises?',type:'chips',req:true,col:2,options:['Own','Lease','Home-based','No fixed location']},
    {k:'squareFootage',label:'Square footage occupied (optional)',type:'text',req:false,col:1,ph:'2,500'},
    {k:'operatingStates',label:'States you operate in (optional)',type:'text',req:false,col:1,ph:'MO, plus any others'},
  ]},
  { id:'coverage', icon:'shield', title:'Coverage you need', desc:"Pick the lines you're interested in — we write all of these.", fields:[
    {k:'linesNeeded',label:'Which coverages do you want?',type:'multi',req:true,col:2,options:['General liability','Business owners policy (BOP)','Commercial property','Commercial auto','Workers’ compensation','Professional liability (E&O)','Cyber liability','Commercial umbrella','Liquor liability','Inland marine / tools & equipment','Directors & officers (D&O)'],help:'Select all that apply — we’ll advise on what your operation needs.'},
    {k:'glLimit',label:'General liability limit',type:'select',req:true,col:1,options:['Not sure — advise me','$500,000','$1M / $2M aggregate','$2M / $4M aggregate'],help:'Per occurrence / aggregate.'},
    {k:'propertyValue',label:'Property / contents to insure',type:'select',req:true,col:1,options:['No property to insure','Under $100k','$100k–$500k','$500k–$1M','Over $1M']},
    {k:'deductible',label:'Preferred deductible',type:'select',req:true,col:1,options:['$500','$1,000','$2,500','$5,000','$10,000']},
    {k:'umbrellaLimit',label:'Umbrella / excess limit',type:'select',req:false,col:1,options:['None','$1M','$2M','$5M','Over $5M']},
  ]},
  { id:'operations', icon:'wrench', title:'Property & operations', desc:'A few details about where and how you operate.', fields:[
    {k:'buildingOwnership',label:'Physical location',type:'select',req:true,col:1,options:['No physical location','Own the building','Lease the space']},
    {k:'buildingValue',label:'Building value if owned (optional)',type:'text',req:false,col:1,ph:'$350,000'},
    {k:'bppValue',label:'Business personal property value (optional)',type:'text',req:false,col:1,ph:'Contents, equipment, inventory'},
    {k:'yearBuilt',label:'Year building built (optional)',type:'text',req:false,col:1,ph:'2004'},
    {k:'constructionType',label:'Construction type',type:'select',req:false,col:1,options:['Frame','Joisted masonry','Masonry non-combustible','Fire resistive','Not sure']},
    {k:'fireProtection',label:'Fire sprinklers / alarm?',type:'select',req:false,col:1,options:['None','Fire alarm','Sprinklers','Both','Monitored']},
    {k:'usesSubcontractors',label:'Do you use subcontractors?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'handlesHazmat',label:'Handle hazardous materials?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'offsiteWork',label:'Do work off-site or make deliveries?',type:'chips',req:true,col:2,options:['Yes','No']},
  ]},
  { id:'history', icon:'truck', title:'Vehicles & history', desc:'Last bit — your fleet and prior coverage.', fields:[
    {k:'numVehicles',label:'Commercial vehicles',type:'select',req:true,col:1,options:['None','1–2','3–5','6–10','More than 10']},
    {k:'currentlyInsured',label:'Currently insured for these lines?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'currentCarrier',label:'Current / most recent carrier',type:'text',req:false,col:1,ph:'e.g. The Hartford'},
    {k:'expirationDate',label:'Current policy expiration',type:'date',req:false,col:1},
    {k:'priorClaims',label:'Claims in the last 3 years',type:'select',req:true,col:1,options:['0','1','2','3 or more']},
    {k:'lossRuns',label:'Can you provide loss runs?',type:'chips',req:false,col:1,options:['Yes','No','Not sure']},
    {k:'startDate',label:'Desired coverage start date',type:'date',req:true,col:1},
    {k:'notes',label:'Anything else we should know?',type:'textarea',req:false,col:2,ph:'Special operations, certificates needed, additional locations, contracts requiring specific limits…'},
  ]},
] };

export const WORKERS_COMP: ProductSchema = { product: "Workers' Comp", code: 'WC', refIdPrefix: 'WC-', steps: [
  { id:'contact', icon:'user', title:'About you & your business', desc:"Who are we quoting, and how do we reach you?", fields:[
    {k:'firstName',label:'First name',type:'text',req:true,col:1},
    {k:'lastName',label:'Last name',type:'text',req:true,col:1},
    {k:'title',label:'Your title / role',type:'text',req:true,col:1,ph:'Owner, HR, Office manager'},
    {k:'phone',label:'Phone',type:'tel',req:true,col:1,ph:'(573) 000-0000'},
    {k:'email',label:'Email',type:'email',req:true,col:1,ph:'you@business.com'},
    {k:'businessName',label:'Legal business name',type:'text',req:true,col:1,ph:'ACME LLC'},
    {k:'fein',label:'FEIN (optional)',type:'text',req:false,col:1,ph:'XX-XXXXXXX'},
    {k:'ssn',label:'Owner Social Security number',type:'text',req:true,col:1,ph:'XXX-XX-XXXX',help:'Used for owner verification and carrier-required reports. Handled per our privacy policy.'},
    {k:'dlNumber',label:'Owner’s driver’s license number',type:'text',req:true,col:1},
    {k:'street',label:'Business address',type:'text',req:true,col:2,ph:'Primary business street address'},
    {k:'city',label:'City',type:'text',req:true,col:1},
    {k:'state',label:'State',type:'select',req:true,col:1,options:STATES},
    {k:'zip',label:'ZIP code',type:'text',req:true,col:1,ph:'63869'},
  ]},
  { id:'business', icon:'building', title:'Your business', desc:'The basics carriers need to classify your policy correctly.', fields:[
    {k:'entityType',label:'Business entity type',type:'select',req:true,col:1,options:['Sole proprietor','Partnership','LLC','S-Corporation','C-Corporation','Non-profit']},
    {k:'businessType',label:'Type of business / industry',type:'text',req:true,col:1,ph:'e.g. Roofing contractor, medical office'},
    {k:'yearsInBusiness',label:'Years in business',type:'select',req:true,col:1,options:['Startup / under 1 year','1–3 years','3–5 years','5–10 years','More than 10 years']},
    {k:'statesOperated',label:'States where employees work',type:'text',req:true,col:1,ph:'MO, AR, TN'},
    {k:'multiState',label:'Single or multiple states?',type:'chips',req:true,col:2,options:['Single state','Multiple states']},
    {k:'governingClassCode',label:'Governing class code, if known (optional)',type:'text',req:false,col:2,ph:'e.g. 5551'},
  ]},
  { id:'payroll', icon:'users', title:'Payroll & employees', desc:'Workers’ comp is rated on payroll by job type — be as specific as you can.', fields:[
    {k:'numFullTime',label:'Full-time employees',type:'select',req:true,col:1,options:['0','1–5','6–10','11–25','26–50','More than 50']},
    {k:'numPartTime',label:'Part-time / seasonal employees',type:'select',req:true,col:1,options:['0','1–5','6–10','11–25','More than 25']},
    {k:'ownersIncluded',label:'Include owners / officers in coverage?',type:'chips',req:true,col:2,options:['Yes','No','Some']},
    {k:'jobDuties',label:'Describe the main job duties',type:'textarea',req:true,col:2,ph:'e.g. 4 field installers, 2 drivers, 1 office admin — list roles and rough headcount'},
    {k:'annualPayroll',label:'Estimated annual payroll',type:'select',req:true,col:1,options:['Under $50k','$50k–$150k','$150k–$500k','$500k–$1M','Over $1M']},
    {k:'clericalPayroll',label:'Clerical / office payroll (optional)',type:'text',req:false,col:1,ph:'Portion that is office-only'},
    {k:'highestRisk',label:'Highest-risk work performed',type:'select',req:true,col:1,options:['Office / clerical only','Light labor','Skilled trades','Heavy / hazardous labor','Roofing / work at height']},
    {k:'subcontractors',label:'Do you use subcontractors?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'certsFromSubs',label:'Collect certificates of insurance from subs?',type:'chips',req:false,col:2,options:['Yes','No','N/A']},
  ]},
  { id:'history', icon:'alert', title:'History & safety', desc:'Your claims history and safety practices shape your experience rating.', fields:[
    {k:'currentlyInsured',label:'Currently have workers’ comp?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'currentCarrier',label:'Current / most recent carrier',type:'text',req:false,col:1,ph:'e.g. Missouri Employers Mutual'},
    {k:'expirationDate',label:'Current policy expiration',type:'date',req:false,col:1},
    {k:'expMod',label:'Experience mod, if known (optional)',type:'text',req:false,col:1,ph:'e.g. 1.00'},
    {k:'priorClaims',label:'WC claims in the last 3 years',type:'select',req:true,col:1,options:['0','1','2','3 or more']},
    {k:'lapse',label:'Any lapse in coverage?',type:'chips',req:true,col:1,options:['No lapse','Yes — currently lapsed','New business']},
    {k:'safetyProgram',label:'Written safety program?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'drugFree',label:'Drug-free workplace program?',type:'chips',req:false,col:1,options:['Yes','No']},
    {k:'oshaIncidents',label:'OSHA recordable incidents (last yr)',type:'select',req:false,col:2,options:['0','1','2','3 or more']},
  ]},
  { id:'coverage', icon:'sliders', title:'Coverage details', desc:'Final details and any special requirements from your contracts.', fields:[
    {k:'effectiveDate',label:'Desired effective date',type:'date',req:true,col:1},
    {k:'waiverSubrogation',label:'Need a waiver of subrogation?',type:'chips',req:true,col:1,options:['Yes','No','Not sure']},
    {k:'additionalStates',label:'Additional states to add (optional)',type:'text',req:false,col:1,ph:'States for out-of-state jobs'},
    {k:'blanketWaiver',label:'Need a blanket waiver for contracts?',type:'chips',req:false,col:1,options:['Yes','No']},
    {k:'certsNeeded',label:'Need certificates of insurance issued?',type:'chips',req:false,col:2,options:['Yes','No']},
    {k:'notes',label:'Anything else we should know?',type:'textarea',req:false,col:2,ph:'Contract requirements, general contractors requiring coverage, upcoming hires, seasonal changes…'},
  ]},
] };

export const LANDLORD: ProductSchema = { product: 'Landlord', code: 'LND', refIdPrefix: 'LND-', steps: [
  { id:'contact', icon:'user', title:'You & the rental property', desc:"Who owns it, and where's the rental? We'll use this to reach you.", fields:[
    {k:'firstName',label:'First name',type:'text',req:true,col:1},
    {k:'lastName',label:'Last name',type:'text',req:true,col:1},
    {k:'phone',label:'Phone',type:'tel',req:true,col:1,ph:'(573) 000-0000'},
    {k:'email',label:'Email',type:'email',req:true,col:1,ph:'you@email.com'},
    {k:'ssn',label:'Social Security number',type:'text',req:true,col:1,ph:'XXX-XX-XXXX',help:'Used to pull carrier-required reports (claims and insurance history). Handled per our privacy policy.'},
    {k:'dlNumber',label:'Driver’s license number',type:'text',req:true,col:1},
    {k:'street',label:'Rental property address',type:'text',req:true,col:2,ph:'Street address of the property to insure'},
    {k:'city',label:'City',type:'text',req:true,col:1},
    {k:'state',label:'State',type:'select',req:true,col:1,options:STATES},
    {k:'zip',label:'ZIP code',type:'text',req:true,col:1,ph:'63869'},
    {k:'mailingAddress',label:'Your mailing address',type:'chips',req:true,col:1,options:['Same as rental','Different']},
  ]},
  { id:'property', icon:'home', title:'About the property', desc:'Tell us about the building you want to insure.', fields:[
    {k:'propertyType',label:'Property type',type:'select',req:true,col:1,options:['Single-family rental','Duplex','Triplex / Fourplex','Apartment (5+ units)','Condo unit','Townhouse']},
    {k:'numUnits',label:'Number of rental units',type:'select',req:true,col:1,options:['1','2','3','4','5 or more']},
    {k:'yearBuilt',label:'Year built',type:'text',req:true,col:1,ph:'1985'},
    {k:'squareFootage',label:'Square footage',type:'text',req:true,col:1,ph:'1,400'},
    {k:'stories',label:'Number of stories',type:'select',req:true,col:1,options:['1','1.5','2','3 or more']},
    {k:'ownershipLength',label:'How long have you owned it?',type:'select',req:true,col:1,options:['Buying now / closing soon','Less than 1 year','1–5 years','5–10 years','More than 10 years']},
    {k:'constructionType',label:'Construction type',type:'select',req:true,col:1,options:['Wood frame','Brick / masonry','Brick veneer','Stucco','Other']},
    {k:'roofType',label:'Roof material',type:'select',req:true,col:1,options:['Asphalt shingle','Metal','Tile','Flat / membrane','Other']},
    {k:'roofAge',label:'Roof age',type:'select',req:true,col:1,options:['0–5 years','6–10 years','11–15 years','16–20 years','Over 20 years','Not sure']},
    {k:'foundationType',label:'Foundation type',type:'select',req:true,col:1,options:['Slab','Crawl space','Full basement','Pier & beam']},
  ]},
  { id:'rental', icon:'key', title:'The rental situation', desc:'How the property is rented affects coverage and price.', fields:[
    {k:'occupancy',label:'How is it occupied?',type:'select',req:true,col:1,options:['Long-term tenant','Short-term / Airbnb','Seasonal','Vacant / between tenants','Owner-occupied + rented rooms']},
    {k:'leaseType',label:'Lease type',type:'select',req:true,col:1,options:['12-month lease','Month-to-month','Short-term (nightly/weekly)','Section 8 / assisted']},
    {k:'monthsRented',label:'Months rented per year',type:'select',req:true,col:1,options:['12','9–11','6–8','Under 6']},
    {k:'monthlyRent',label:'Monthly rent collected',type:'text',req:true,col:1,ph:'$1,200'},
    {k:'tenantScreening',label:'Do you screen tenants?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'utilitiesPaidBy',label:'Who pays utilities?',type:'select',req:false,col:1,options:['Tenant','Landlord','Split']},
    {k:'furnished',label:'Is it furnished?',type:'chips',req:true,col:2,options:['Unfurnished','Furnished','Partially furnished']},
  ]},
  { id:'systems', icon:'wrench', title:'Systems & risk', desc:'Condition and protection details carriers rate on.', fields:[
    {k:'heatingType',label:'Primary heat source',type:'select',req:true,col:1,options:['Forced air (gas)','Forced air (electric)','Heat pump','Boiler / radiant','Baseboard electric']},
    {k:'electricalUpdated',label:'Electrical updated in last 25 yrs?',type:'chips',req:true,col:1,options:['Yes','No','Not sure']},
    {k:'plumbingUpdated',label:'Plumbing updated in last 25 yrs?',type:'chips',req:true,col:1,options:['Yes','No','Not sure']},
    {k:'distanceToFireStation',label:'Distance to nearest fire station',type:'select',req:true,col:1,options:['Under 1 mile','1–5 miles','Over 5 miles','Not sure']},
    {k:'distanceToHydrant',label:'Distance to nearest hydrant',type:'select',req:true,col:1,options:['Under 500 ft','500–1000 ft','Over 1000 ft','No hydrant nearby']},
    {k:'pool',label:'Swimming pool on the property?',type:'chips',req:true,col:1,options:['None','Above-ground','In-ground']},
    {k:'smokeDetectors',label:'Smoke detectors in the unit(s)?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'floodZone',label:'Is the property in a flood zone?',type:'chips',req:true,col:2,options:['Yes','No','Not sure'],help:'Standard landlord policies don’t cover flood — we can quote separate flood coverage if needed.'},
  ]},
  { id:'coverage', icon:'sliders', title:'Coverage & history', desc:"The coverage you want and your recent history. We'll fine-tune specifics on our call.", fields:[
    {k:'dwellingCoverage',label:'Dwelling coverage (rebuild cost)',type:'select',req:true,col:1,options:['Not sure — help me','Under $150k','$150k–$250k','$250k–$400k','$400k–$600k','Over $600k'],help:'What it would cost to rebuild, not market value.'},
    {k:'lossOfRents',label:'Loss of rents coverage',type:'select',req:true,col:1,options:['Not sure','6 months','12 months','Actual loss sustained'],help:'Replaces rental income if the property becomes uninhabitable after a covered loss.'},
    {k:'liabilityLimit',label:'Liability limit',type:'select',req:true,col:1,options:['$100,000','$300,000','$500,000','$1,000,000']},
    {k:'deductible',label:'Preferred deductible',type:'select',req:true,col:1,options:['$500','$1,000','$2,500','$5,000']},
    {k:'personalProperty',label:'Landlord contents coverage',type:'select',req:false,col:1,options:['None','Appliances only','Furnished contents']},
    {k:'currentlyInsured',label:'Currently insured?',type:'chips',req:true,col:1,options:['Yes','No']},
    {k:'currentCarrier',label:'Current / most recent carrier',type:'text',req:false,col:1,ph:'e.g. Foremost, Shelter'},
    {k:'claims3yr',label:'Claims in the last 3 years',type:'select',req:true,col:1,options:['0','1','2','3 or more']},
    {k:'endorsements',label:'Coverage add-ons you want',type:'multi',req:false,col:2,options:['Loss of rents','Vandalism / malicious mischief','Ordinance or law','Water backup','Equipment breakdown','Building code upgrade'],help:'Pick any that interest you.'},
    {k:'startDate',label:'When do you want coverage to start?',type:'date',req:true,col:1},
    {k:'notes',label:'Anything else we should know?',type:'textarea',req:false,col:2,ph:'Multiple rental properties to bundle, recent renovations, detached structures, HOA requirements…'},
  ]},
] };

export const PRODUCT_SCHEMAS = { auto: AUTO, home: HOME, commercial: COMMERCIAL, 'workers-comp': WORKERS_COMP, landlord: LANDLORD };
